---
- name: Save every inventory host into /etc/hosts
  vars:
    - block_content: >
        {% if not ih_clear %}

        {% for item in groups.all %}
        {% if not item | ipaddr %}
        {{
          ih_host_ip[item] if ih_host_ip[item] is defined else
          hostvars[item]['ansible_' + ih_host_interface[item]].ipv4.address if ih_host_interface[item] is defined else
          hostvars[item]['ansible_default_ipv4']['address'] if hostvars[item]['ansible_default_ipv4'] is defined else
          lookup('dig',item)
        }}
        {{
          ih_host_name[item] if ih_host_name[item] is defined else
          item
        }}

        {% endif %}
        {%- endfor %}

        {% for item in ih_extra_hosts %}
        {{ ih_extra_hosts[item] }} {{ item }}

        {%- endfor %}

        {% endif %}
  blockinfile: block="{{ block_content }}" dest="/etc/hosts" marker="##### {mark} {{ ih_signature }}" \
                 create=true state={{ "present" if not ih_clear else "absent"  }}
